services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: always
    environment:
      - REALM=localhost
      - USERNAME=admin
      - PASSWORD=194393
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
